export type experienceType = {
  id: string;
  company: string;
  jobRole: string;
  time: string;
  location: string;
  points: string[];
};

export const experiences: experienceType[] = [
  {
    id: "1",
    company: "Deloitte US India",
    jobRole: "Data Engineer",
    time: "Sep 2022 - Present",
    location: "Bengaluru, India",
    points: [
      "Developed Python automation scripts using libraries like 'pyautogui' to validate data outputs with client-provided Excels, significantly boosting team productivity by automating manual checks.",
      "Engineered a Python program to automate the formatting of complex visuals by analyzing and manipulating the underlying XML structure generated by reporting tools.",
      "Built a Python solution for robust data handling, enabling insertion and updates into databases by programmatically managing errors present in flat file data sources.",
      "Implemented a concise Javascript solution to automate repetitive UI interactions (selecting 1000s of security assignments), resulting in an estimated 100x productivity increase and eliminating a highly tedious manual task.",
      "Designed and implemented data integration processes using Oracle Fusion Data Intelligence (FDI), modelling data from diverse sources to create unified structures for application use.",
      "Developed 25+ interactive, data-driven dashboards and reports in Oracle Analytics Cloud (OAC) across various clients, translating complex data into actionable insights for stakeholders.",
      "Applied performance optimization techniques to drastically reduce report/application load times, achieving improvements from ~6 minutes down to 8 seconds.",
      "Collaborated effectively with business stakeholders to gather, clarify, and translate requirements into technical specifications, managing 100+ user stories throughout project lifecycles.",
      "Consistently delivered high-quality technical solutions for diverse clients, earning Applause and Outstanding Performance Awards, and receiving a Special Shoutout in Deloitte’s Data Intelligence newsletter.",
      "Served as the primary Point-of-Contact on a recent client project, demonstrating technical ownership and strong communication skills.",
    ],
  },
].reverse();
